Resources/Prototypes/Loadouts/Jobs/service.yml

Added Bunny Suit and Bunny Ears to bartender's loadout. -You're welcome, Mars
---
:cl:
- add: Bunny Suit to Bartender's loadout
- add: Bunny Ears to Bartender's loadout

Added Bunny Suit and Bunny Ears to bartender's loadout

---

Resources/Changelog/Changelog.yml
Resources/Changelog/Floof.yml
Resources/Locale/en-US/changelog/changelog-window.ftl

Add a special Floof Station Changlog so EE/Floof are seperated, mostly for Workflow.
<p>
</p>
</details>

Floof Station Changlog

---

Resources/Prototypes/Entities/Mobs/Species/human.yml

Oops deleted this by mistake.
<p>
N/A
</p>
</details>
---
:cl: FoxxoTrystan
- fix: Humans can now understand sol common again!

Fix Human Sol-Common

---

Resources/Locale/en-US/traits/traits.ftl

During the #9 PR, a merge conflict made issues with trait .ftl file, overrinding it, this PR fixes the issue.
---
:cl: FoxxoTrystan
- fix: Fixed missing Psionic traits name/descriptions

Fix missing Psionic FTL

---

Resources/Prototypes/Nyanotrasen/GameRules/events.yml

Remove the Mass-Mind-Swap event that is causing a ton of issues.
---
:cl:
- remove: Removed Mass-Mind-Swap Event.

Remove Mass-Mind-Swap

---

Resources/ServerInfo/Rules.txt

:cl:
- tweak: Added, tweaked or removed a few rules. Also finally should have a modicum of formatting.

Rules Update

---

Content.Server/Chat/Systems/ChatSystem.cs
Content.Shared/Language/LanguagePrototype.cs
Resources/Locale/en-US/language/languages.ftl
Resources/Locale/en-US/language/sign-language.ftl
Resources/Prototypes/Language/languages.yml

Merge PR https://github.com/Simple-Station/Einstein-Engines/pull/553
Required for #31 
---
:cl:
- add: Sign Languages!

Sign Language

---

Resources/Prototypes/FloofStation/Entities/Mobs/NPCs/scugcat.yml

Scugs can no longer go under door but also this patch make them able to resist grabs, able to go in bags and the AI will hunt Mices by default.
---
:cl:
- add: Scugs can now go in bags and resist grabs!
- fix: Scugs cannot fit under doors anymore.

Scug Patch

---

Resources/Locale/en-US/devices/device-network.ftl
Resources/Locale/en-US/reagents/meta/consumable/drink/alcohol.ftl
Resources/Locale/en-US/revenant/revenant.ftl
Resources/Locale/en-US/weapons/melee/melee.ftl
Resources/Prototypes/FloofStation/Entities/Objects/Consumable/Drinks/drinks_bottles.yml

Changed item description as well as some comment whitespace that made vscode mad.
---
:cl: Tilkku
- tweak: Description for bottleocum

Minor Changes to Bartender Descriptions & Comment Errors

---

Resources/Prototypes/Catalog/VendingMachines/Inventories/cola.yml
Resources/Prototypes/Catalog/VendingMachines/Inventories/gib.yml
Resources/Prototypes/Catalog/VendingMachines/Inventories/pwrgame.yml
Resources/Prototypes/Catalog/VendingMachines/Inventories/shamblersjuice.yml
Resources/Prototypes/Catalog/VendingMachines/Inventories/sovietsoda.yml
Resources/Prototypes/Catalog/VendingMachines/Inventories/spaceup.yml
Resources/Prototypes/Catalog/VendingMachines/Inventories/starkist.yml
Resources/Prototypes/FloofStation/Reagents/Drinks/drinks.yml

Adds "Nikko's Naughty Nectar" to more vending machines and modifies the reagent to have an aphrodisiac effect.
---
---
:cl:
- tweak: Nikko's Naughty Nectar now has an aphrodisiac effect
- tweak: Nikko's Naughty Nectar has been added to more vending machines.

NNN Modifications and Vending

---

Resources/Prototypes/Recipes/Lathes/medical.yml

Added cane for the blind to the medifab, so CentCom can do less work! Basically same as upstream code.
---
:cl: Xavier
- add: Canes for the blind to Medifab.

Added Upstream White Cane Recipe to Medifab

---

Resources/Prototypes/Entities/Structures/Machines/lathe.yml

Ok, so last PR for this exact thing was that I added a recipe for, I forgot to actually PUT the recipe into the medical fab, so it's there now. Also, yes I did this really quickly so I accidentally wrote a description in my commit name and I do NOT know how to change it. Sorry again if I'm unnecessarily flooding the PR's with small changes!
---
:cl: Xavier
- fix: White Cane not appearing in Medifab.

Put White Cane Recipe Into the Medifab

---

Resources/Prototypes/Floof/Entities/Clothing/Uniforms/misc.yml

Changed the parent of loincloth to skirts, so now harpies can wear them!
---
<p>
</p>
</details>
---
:cl:
- fix: harpies can now wear loincloth :3

Harpies Can Now Wear Loin Cloth!

---

Resources/Prototypes/Recipes/Cooking/medical_recipes.yml

Changed the cooking time for aloe cream, so now it doesn't interfere with RegenerativeMesh any longer. Quick note-- this isn't Floof marked as it will match upstream, I just wanted this merged faster.
:cl:
- fix: Fixed the RegenMesh recipe

Aloe Cream Change

---

Resources/Prototypes/Catalog/VendingMachines/Inventories/cola.yml

Added red bool energy drink back into vending machines

Red Bool Fix

---

Resources/Locale/en-US/ghost/roles/ghost-role-component.ftl

Changed the wording on the skeleton to match with Delta-V,
The wording on the skeleton ghost role is a contradiction with the server rules, so I changed it to more fit with what it should be, matching with what DeltaV has put for them.
---
:cl:
- tweak: Skeletons are no longer inherently evil

De-Antag Skeletons

---

Resources/Prototypes/Floof/Reagents/Aphrodisiacs/medicine.yml
Resources/Prototypes/Floof/Reagents/Aphrodisiacs/narcotics.yml

This changes all the aphrodisiacs metabolism rates to 0.03u/second. This makes 10u of each last longer than 5 minutes.
---
:cl:
- tweak: Our chaplain prayed to the Deity of Lust, and now aphrodisiacs last much much longer

Longer Lasting Aphrodisiacs

---

Resources/Prototypes/Floof/Recipes/Reactions/drinks.yml

somehow i forgot to add a recipe to the loverskiss drink
Added a recipe for the lover's kiss drink
:cl: Tilkku
- fix: Lover's Kiss Recipe

Added Recipe

---

Resources/Locale/en-US/interaction/interaction-popup-component.ftl
Resources/Prototypes/DeltaV/Entities/Mobs/Player/vulpkanin.yml
Resources/Prototypes/Entities/Mobs/Player/harpy.yml
Resources/Prototypes/Entities/Mobs/Species/base.yml
Resources/Prototypes/Nyanotrasen/Entities/Mobs/Player/Oni.yml
Resources/Prototypes/Nyanotrasen/Entities/Mobs/Player/felinid.yml

This PR returns hugs until this PR will again nuke it: https://github.com/Simple-Station/Einstein-Engines/pull/733
---
:cl:
- add: Hugs have returned!

Return of the Hugs

---

Resources/Prototypes/Floof/Loadouts/eyes.yml

Re-adds the goggles in loadouts, that were not added in the upstream merge
---
:cl:
- add: Cosmetic Goggles are available in loadouts again

Goggles In Loadouts Again

---

Content.Client/UserInterface/Systems/EscapeMenu/EscapeUIController.cs

Removed Belpstation advertisement due to Wizden requirements.

Removed Blepstation Advertisement

---

Resources/Prototypes/Floof/Recipes/Reactions/drinks.yml

Description.
Added Sake Recipe rice plus enzyme
<p>
</p>
</details>
:cl:
- add: Sake Recipe

Added Sake Recipe

---

Resources/Prototypes/Maps/glacier.yml

Adds justice roles to Glacier.
Description.
---
Glacier already has a fully mapped in justice department, it just lacks the roles.
---
<p>
</p>
</details>
---
:cl:
- fix: Fixed Glacier not having its Justice Roles

Add Justice Roles to Glacier

---

Resources/ServerInfo/Guidebook/Science/Robotics.xml

Description.
Text update for Roboticist 
added the responsibility of the maintenance of IPCs
:cl:
- tweak: Roboticist Guide Book Text

Updated Roboticist Text 

---

Resources/Prototypes/Entities/Mobs/NPCs/dogs.yml

This PR makes Pitbulls SimpleNeutral faction, and also, gets rid of their aggresiveness, 
---
:cl:
- tweak: Pitbulls are now neutral to all crew.

Pitbulls Are Friendly

---

Resources/Prototypes/Catalog/Fills/Lockers/misc.yml
Resources/Prototypes/Floof/Catalog/Fills/Crates/lewd.yml

Adds Whips and Paddles to the lockers.
---
:cl:
- add: Whips and Paddles to lockers.

Quickly Adds New Items to Lockers

---

Resources/Prototypes/Traits/disabilities.yml
Resources/Prototypes/Traits/physical.yml
Resources/Prototypes/Traits/skills.yml

This PR changes the cost of a few traits, and makes parkour training feel more meaningful (but it's ultimately cheaper)
I will say that not ALL of these are quite equal, but there has been some equalization.
---
:cl:
- tweak: Many trait costs have been cheapened, some traits have been changed.

Trait Rebalance

---

Resources/ConfigPresets/Build/debug.toml

Fixes the issue with events not running on survival.
---
:cl:
- fix: Survival not creating events.

Should Fix Events

---

Resources/Prototypes/game_presets.yml

This PR puts thieves in the two new gamemodes and also the secret extended preset. If EE wants this, please port it yourselves, I am too focused on Floof right now.
---
:cl:
- add: Thieves are showing up more often again...

Thieves In More Gamemodes

---

Resources/Prototypes/Floof/Traits/physical.yml

Changes Vampirism to cost points instead of give points.
---
:cl:
- tweak: Vampirism costs three points.

Change Vampirism to Coset 3 Points

---

Resources/ServerInfo/Guidebook/Mobs/IPCs.xml

This PR updates the IPC guidebook to clarify they should be taken to Epistemics and repaired by the Roboticist (or Epistemics in general).
---
:cl:
- tweak: Clarified where IPCs should go for repairs in their guidebook.

Update IPC Guidebook

---

Resources/Prototypes/Nyanotrasen/Species/felinid.yml

This PR makes felinids be able to change their skin color to hues instead of human. Literally copying from this PR: https://github.com/DeltaV-Station/Delta-v/pull/1783
Leonardo DaBepis brought this to my attention.
I am on mobile so cannot cherrypick or whatever.
Thanks for the cool idea DeltaV!
---
:cl:
- tweak: Felinids can now be multiple colors instead of human colors.

Felinid Hues

---

Resources/Prototypes/XenoArch/Effects/normal_effects.yml

Changes Depth for station-destruction from 8 to 9
---
:cl:
- tweak: Depth changed from 8 to 9.

Upped the Depth From 8 to 9

---

Resources/Prototypes/Entities/Markers/Spawners/Random/artifacts.yml
Resources/Prototypes/Entities/Objects/Specific/Xenoarchaeology/item_artifacts.yml

This PR disables Omen-level Item Artifacts.
---
:cl:
- remove: Omen Item Artifacts.

Disable Omen Artifact Items

---

Resources/Prototypes/Entities/Mobs/NPCs/Rslimes.yml
Resources/Prototypes/Entities/Mobs/NPCs/xenopet.yml

This is a hotfix of the spawn rate for the different Vent critters events. 
---
:cl:
- tweak: Tweaked spawn rates of Various Ventcritter Spawn events

Vent Spawn Hotfix

---

Resources/Prototypes/DeltaV/Roles/Jobs/Justice/chief_justice.yml
Resources/Prototypes/DeltaV/Roles/Jobs/Security/brigmedic.yml
Resources/Prototypes/Entities/Mobs/Customization/Markings/shadowkin.yml
Resources/Prototypes/Entities/Mobs/Species/shadowkin.yml
Resources/Prototypes/Nyanotrasen/Roles/Jobs/Security/prisonguard.yml
Resources/Prototypes/Nyanotrasen/Roles/Jobs/Wildcards/prisoner.yml
Resources/Prototypes/Roles/Antags/Thief.yml
Resources/Prototypes/Roles/Antags/revolutionary.yml
Resources/Prototypes/Roles/Antags/traitor.yml
Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml
Resources/Prototypes/Roles/Jobs/Command/captain.yml
Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
Resources/Prototypes/Roles/Jobs/Engineering/chief_engineer.yml
Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml
Resources/Prototypes/Roles/Jobs/Security/detective.yml
Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml
Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
Resources/Prototypes/Roles/Jobs/Security/senior_officer.yml
Resources/Prototypes/Roles/Jobs/Security/warden.yml
Resources/Prototypes/Species/shadowkin.yml
Resources/Prototypes/Traits/species.yml

Allow peoples to pick shadowkin as their playerable race, tho blackeyed with no powers.
Power version is still undergoing some tests tho admins can still set any shadowkin with powers.
---
:cl:
- add: Blackeye-Shadowkins!

Blackeye-Shadowkin

---

Content.Server/Shadowkin/ShadowkinSystem.cs
Content.Shared/Humanoid/EyeColor.cs
Content.Shared/Humanoid/SharedHumanoidAppearanceSystem.cs

EyeColorFix

---

Resources/Prototypes/Voice/speech_emotes.yml

I will be completely real, I made this during a shift cause tech said "bet" and I made it while on shift. So, this adds the two chat triggers for making your character weh, nothing else needs to be added since all the characters that can weh have it in their files already. Tested it, it works.
---
---
<p>
</p>
</details>
---
:cl: Xavier
- add: You can now weh to your heart's content!

Added Weh Chat Trigger

---

Content.Client/Lobby/UI/HumanoidProfileEditor.xaml.cs
Resources/Prototypes/DeltaV/Species/rodentia.yml
Resources/Prototypes/DeltaV/Species/vulpkanin.yml
Resources/Prototypes/Nyanotrasen/Species/Oni.yml
Resources/Prototypes/Nyanotrasen/Species/felinid.yml

Simply add the custom specie name variable to some missing specie.
---
:cl:
- add: Enable Custom Specie Name for, Vulp, Felinds, Oni, Rodentia.

Custom Specie Name for all!

---

Content.Client/HealthAnalyzer/UI/HealthAnalyzerWindow.xaml.cs
Resources/Locale/en-US/deltav/ghost/roles/ghost-role-component.ftl
Resources/Locale/en-US/ghost/roles/ghost-role-component.ftl
Resources/Locale/en-US/traits/traits.ftl

This is a quick PR to fix a few localization issues.
This includes:
- The health analyzer
- Shiva ghost role
- Tarantula ghost role
- kα Deficiency description.
---
:cl:
- fix: Health Analyzer damage types, Shiva and Tarantula ghost roles, and the kα Deficiency description.

Fixes some localization files and the Health Analyzer window.

---

Resources/Prototypes/DeltaV/Entities/Mobs/NPCs/pets.yml

Simply adds  the ability for Laika to track scents like Vulps!
---
:cl:
- add: Added the ability for Laika to track scents.

Added scent Tracking to Laika

---

Resources/Changelog/Floof.yml
Resources/ServerInfo/SpaceLaw/SpaceLaw.md

Rape and SA RP are not appropriate on this server and violate our rules of extreme content being made public.  if you wish to RP it where nobody else knows what's going on fine.  but as soon as that door opens it never happened
:cl:
- remove: Rape from law as it is a rules violation.
- remove: Sexual Assault/Harassment from law as it is a rules violation.

Remove Rape and SA From S-LAW

---

Content.Server/Abilities/Psionics/Abilities/DarkSwapSystem.cs
Content.Server/Shadowkin/EtherealSystem.cs
Content.Shared/Shadowkin/EtherealComponent.cs

This PR simply fixes some workflows tests and does nothing directly in-game.
Ethereal Changes: When etheral comp is removed its will not make the shadow effect anymore (this is only triggered by the darkswap ability and not the comp anymore)

Ethereal Build Test Fixes

---

Resources/Maps/Floof/NTNFships/ntnfhummingbird.yml
Resources/Maps/Floof/NTNFships/ntnfrook.yml
Resources/Maps/Floof/NTNFships/ntnwasp.yml

A project relating to potential future ERTs and a branch of NanoTrasen dubbed the "NanoTrasen Naval Force" Acts as an ert and a current placeholder for future reworks and implementation. Currently admin spawn only.

NTNF (ERT)

---

Resources/Prototypes/Floof/Recipes/Reactions/drinks.yml

Changed dark oasis recipe. Only requires 1 cocoa powder now, at request of @LavaHIt100 on the discord.
---
:cl:
- tweak: Tweaked Dark Oasis Recipe

Changed Dark Oasis Recipe

---

Resources/Prototypes/Floof/Catalog/Cargo/cargo_fun.yml

Price update as requested
---
:cl:
- tweak: Tweaked Price

Companion Crate Price Update

---

Content.Server/Dragon/DragonSystem.cs
Resources/Locale/en-US/ghost/roles/ghost-role-component.ftl

Removed timer from Space dragon to promote more opportunity for roleplay 
---
:cl:
- remove: Removed timer from dragon gameplay

Remove Dragon Timer

---

Resources/Prototypes/Floof/Entities/Mobs/NPCs/Drake.yml

Renamed adolescent space dragon to Drakes or Space Drakes as well as put the Leashanchor onto the space drake for testing 
---
:cl:
- add: Added Leash anchor to Space drakes
- tweak: Tweaked the name of Space drakes

Update and Rename Adolescent Dragon to Drake

---

.github/workflows/publish-stable.yml
.github/workflows/publish-testing.yml
Content.Server/Communications/CommunicationsConsoleSystem.cs
Content.Shared/Interaction/SharedInteractionSystem.cs
Resources/Changelog/Floof.yml
Resources/Prototypes/Catalog/Fills/Lockers/misc.yml
Resources/Prototypes/Maps/glacier.yml

contains fixes 
#377
#379
#378

Floofstation Release V6

---

Resources/Prototypes/Roles/Jobs/Command/captain.yml

Whitelist the captain job, only merged at the correct time.
---
:cl:
- tweak: Captain job is now whitelisted.

Captain Whitelist

---

Resources/Changelog/Floof.yml
Resources/Prototypes/Roles/Jobs/Command/captain.yml

:cl:
- add: Added captain whitelist

Added Captain Whitelist

---

Resources/Maps/Floof/NTNFships/ntnfhummingbird.yml
Resources/Maps/Floof/NTNFships/ntnfscarab.yml

Fixes known issues with ships, makes them less prone to running out of power, and corrects non-ERT personnel from walking through.

NTNF Ship Update

---

Resources/Prototypes/Catalog/uplink_catalog.yml

Removal of those items were requested.
---
:cl:
- remove: Removed SyndicateBomb, ChinaLake, ZombieBundle

Remove some Uplink Items.

---

Resources/Prototypes/Entities/Objects/Weapons/Melee/pickaxe.yml

This pull request fixes the mining drill to have it's stats back to expected values and performance. 
---
:cl:
- fix: Fixed mining drill

Mining Drill

---

Resources/Prototypes/secret_weights.yml

Altered the gamemodes and Weights of the Secret gamemode as per Fasana's request. 
---
:cl:
- tweak: Tweaked Secret Gamemode

Secret Weights Adjustment

---

Resources/Prototypes/CharacterItemGroups/gloveGroup.yml
Resources/Prototypes/Floof/CharacterItemGroups/gloveGroup.yml
Resources/Prototypes/Loadouts/hands.yml

Top text
Bottom text
:cl: Crow
- add: Added wedding rings to loadouts

Add Wedding Rings to Loadouts

---

Resources/Prototypes/Floof/Entities/Clothing/departmental_clothes.yml
Resources/Prototypes/Loadouts/Jobs/security.yml

Dearest Ellie wanted corps socks  so I made a pr that uses the paramedics socks
:cl:
- add: Corpsman Highsocks as a loadout item

Adds Corps Socks to Sec Loadout

---

Resources/Prototypes/Floof/Entities/Clothing/departmental_clothes.yml

it should have had a slot in the socks for a knife
:cl:
- tweak: Sow a pocket to the side of Corpsman socks

Update to the Corps Sock 

---

Content.Server/Voting/Managers/VoteManager.DefaultVotes.cs
Resources/Locale/en-US/voting/managers/vote-manager.ftl

Adds a new option to map votes that, when it wins, chooses a random map from the pool of eligible maps.
<p>
The actual results
Ignore the minor spelling mistake
</p>
</details>
:cl:
- add: Added a "random map" option to "next map" votings.

Random Map Votes

---

Resources/Maps/Floof/NTNFships/ntnfbee.yml
Resources/Maps/Floof/NTNFships/ntnfscarab.yml

Adds more functionality to the Scarab, adding missing kitchen equipment, removed an extra lightbulb, added materials and basic engineering equipment, added lower dock canister air pumps for possible engineering ERT usage in future. Also added 3 space heaters.
Bee had its atmosphere fixed.
Scarab + Bee now have blue IFF colors. (Hopefully)

Scarab+Bee Update+fixes

---

Resources/Prototypes/Actions/psionics.yml
Resources/Prototypes/Entities/Mobs/NPCs/revenant.yml
Resources/Prototypes/Nyanotrasen/psionicPowers.yml
Resources/Prototypes/Psionics/psionics.yml

added back some functional powers to the spawn pool as well as updated revenant sprite. 
---
:cl:
- add: Added some old powers back
- Tweak: Tweaked the Revenant Sprite

Psionic Tweaks

---

Resources/Maps/Floof/saltern.yml

:cl:
- fix: Fixed incorrect doors either granting access or denying access.

Saltern Door Fix

---

Resources/Prototypes/Species/diona.yml

Adds custom species name to Diona.
---
---
<p>
</p>
</details>
---
:cl:
- tweak: Diona can now have custom species names. Plants rejoice!

Allow Custom Species for Diona

---

Resources/Changelog/Floof.yml

aaaaaaaaaaaaa
---
---
<p>
</p>
</details>
---
:cl:
- fix: Added some more missing changelog entries.

Restore Missing Changelog Entries 2

---

Resources/Locale/en-US/Floof/guidebook/guides.ftl
Resources/Prototypes/Floof/Guidebook/sop.yml
Resources/ServerInfo/Floof/Guidebook/SOP/AlertProcedure.xml
Resources/ServerInfo/Floof/Guidebook/SOP/CommandHierarchy.xml
Resources/ServerInfo/Floof/Guidebook/SOP/GeneralRegulations.xml
Resources/ServerInfo/Floof/Guidebook/SOP/MutinyGuidelines.xml
Resources/ServerInfo/Floof/Guidebook/SOP/Permits.xml
Resources/ServerInfo/Guidebook/Glossary.xml

Adds the Mutiny Guidelines, General Regulations, Command Hierarchy, Alert Procedure, and Permits SOPs from the Floof Wiki to the Guidebook.
Also makes some changes to the Glossary requested by Fae, specifically around some LRP/derogatory terms.
---
---
<p>
</p>
</details>
---
:cl:
- add: Added Floof Mutiny Guidelines, General Regulations, Command Hierarchy, Alert Procedure, and Permits guidebook entries
- tweak: modified the guidebook Glossary

Floof Guidebook Update

---

Resources/Prototypes/Entities/Mobs/Customization/Markings/moth.yml

Fixes moth wings, cause wings are tails. I can fix it the other way if desired, by making all of them wings. Right now the issue is that the default wings are set to tail so like, when you choose a wing that's a wing it doesn't override the tail... wing. So you get both.
If desired I can fix it the other way easy, by making them all wings, though that will cause more conflicts to upstream. Just lemme know if you want me to go the other way!
---
---
<p>
I dunno, I can get pictures if ya really want. Just a quick YAML change.
</p>
</details>
---
:cl:
- fix: Fixes some moth wings not actually replacing the default wings, particularly noticeable with the charred wings.

Fix Moth Wings

---

Content.Client/CrewManifest/UI/CrewManifestSection.cs
Content.Client/Stylesheets/StyleNano.cs
Content.Server/CrewManifest/CrewManifestSystem.cs
Content.Shared/CrewManifest/SharedCrewManifestSystem.cs
Resources/Locale/en-US/deltav/gender.ftl

Adds pronouns to the crew manifest, ported from delta-v who ported it from Impstation. 
https://github.com/DeltaV-Station/Delta-v/pull/2647
Known issue:
https://github.com/DeltaV-Station/Delta-v/issues/2671
---
---
<p>
</p>
</details>
---
:cl: Forzii and TGRCDev
- add: Crew manifest now shows pronouns
- fix: Crew manifest should no longer overlap long names and titles

Add Pronouns to Crew Manifest

---

Content.Client/Entry/EntryPoint.cs
Content.Client/_NF/Emp/Overlays/EmpBlastOverlay.cs
Content.Server/Emp/EmpSystem.cs
Content.Shared/_NF/Emp/Components/EmpBlastComponent.cs
Content.Shared/_NF/Emp/Systems/EmpBlastSystem.cs
Resources/Prototypes/_NF/Entities/Effects/emp.yml
Resources/Prototypes/_NF/Shaders/shaders.yml
Resources/Textures/_NF/Shaders/emp.swsl

Ported a nicer looking EMP effect from Frontier with permission from the code author, @dvir001.
---
https://github.com/user-attachments/assets/9e4a8d6f-cdef-46fe-a471-de20a35e1d5a
---
:cl:
- tweak: EMP Pulse got a new visual look thanks to dvir001!

Add EMP Blast Effect Shader (Frontier #2262)

---

Resources/Prototypes/Floof/Loadouts/Generic/uniform.yml

Title
:cl: Fenny
- add: Gray Jumpskirt added to loadout clothing selection!

Adds Gray Jumpskirt to Loadout

---

Resources/Locale/en-US/Floof/guidebook/guides.ftl
Resources/Prototypes/Floof/Guidebook/sop.yml
Resources/ServerInfo/Floof/Guidebook/SOP/EngineeringStandardOperatingProcedure.xml
Resources/ServerInfo/Floof/Guidebook/SOP/EpistemicsStandardOperatingProcedure.xml
Resources/ServerInfo/Guidebook/ServerRules/RoleTypes.xml

Attempted to floofify the role types entry by request from Fae. Additionally, added Epistemics SOP and Engineering SOP.
---
---
<p>
</p>
</details>
---
:cl:
- add: Epistemics SOP and Engineering SOP guidebook entries
- tweak: Floofed up the Role Types guidebook entry

Guidebook Updates
