Resources/Locale/en-US/info/rules.ftl
Resources/ServerInfo/Rules.txt

Server currently says it's DeltaV in the rules header, this changes that.
:cl:
- fix: Rules header now correctly displays server name.

Fix Rules Header

---

Resources/Prototypes/Loadouts/Jobs/science.yml
Resources/Prototypes/Loadouts/head.yml

Very simple PR. This adds the hairflower and Explorer's labcoat to the head loadout and Epistemics job loadouts respectively. This will go to upstream eventually, I've just got way too much open on that side and don't want to accidentally push kitsune stuff with this, so it gets to come here first
---
---
<p>
</p>
</details>
---
:cl:
- add: Epistemics has been given a supply of new labcoats, and everyone has been authorized to wear hairflowers.

Add Hairflower and Explorer's Labcoat to Loadouts

---

Content.Server/Chemistry/ReagentEffects/ReduceRotting.cs
Content.Shared/Atmos/Rotting/SharedRottingSystem.cs
Resources/Locale/en-US/guidebook/chemistry/effects.ftl
Resources/Locale/en-US/reagents/meta/medicine.ftl
Resources/Prototypes/Reagents/medicine.yml
Resources/Prototypes/Recipes/Reactions/medicine.yml

Added Opporozidone, the chemical that reduces rot, from upsteam! Allows people to be revived even if their bodies are rotting, which reduces the use of cloning and losing your character. The code for this may be a bit botched, as I patched in the Wizden code, which required adding a method from upstream to the sharedRottingSystem. Not sure if it was the right place to put it but the chemical DOES work, so.
---
<p>
</p>
</details>
---
:cl: Xavier
- add: Opporozine, upstream chemical that allows you to remove rotting by cryopods!

Added Opporozidone and ReduceRotting Effect

---

Content.Server/Chat/Systems/ChatSystem.cs

During Sign Language Refractor the wrong value was used, this fix also is needed to be ported to EE.
---
- fix: Whisper

Fix Whisper

---

Resources/Prototypes/Loadouts/eyes.yml

Glasses for everyone, even nearsighted crew. I get the whole point of disuading trading trait points for loadout points, but this server is roleplay focused.
---
:cl:
- add: Glasses are now available for nearsighted crew.

Glasses Are Now Available for Nearsighted Crew

---

Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Resources/Prototypes/Recipes/Lathes/cooking.yml

This adds the Beverage Jugs for the bartender back into the autolathe, as to make them easier to get a hold of for things like juices.
---
:cl: Tilkku
tweak: added beverage jugs to autolathe

Added Beverage Jugs to Lathe

---

Resources/Prototypes/Entities/Clothing/Hands/gloves.yml
Resources/Prototypes/Loadouts/hands.yml
Resources/Prototypes/Loadouts/head.yml
Resources/Prototypes/Loadouts/uniform.yml

Added the Maid outfit, with and without miniskirt, and added the entire Tactical Maid Outfit, removing the insulation of the gloves in the process of manufacturing. All of these are available for everyone except for Security and Command.
---
:cl:
- add: Maid outfits, including the tactical variety, are now available for everyone but Security and Command!
- tweak: Tactical maid gloves are no longer insulated.

The Maid Outfit Loadout Update

---

Resources/Prototypes/Loadouts/items.yml

The civi survival box is now available for Epistemics
---
:cl:
- tweak: Space OSHA has required us to offer Epistemics the option to take a survival box

Epistemics Survival Box

---

Content.Shared/CCVar/CCVars.cs

This PR hopefully changes the default trait limit from 5 to 7. The amount of points you get is left the same. The reason that I am changing it is due to the new lewd trait system. I believe that this server is roleplay-focused enough to where this will not be abused heavily. I believe the point costs of each trait is what balances them all. This is essentially so characters can have tits and a cock along with their normal trait loadouts.
---
:cl:
- tweak: Trait limit changed from 5 to 7.

Increases Trait Limit From 5 to 7

---

Resources/Prototypes/Floof/Entities/Clothing/OuterClothing/wintercoats.yml

Fixed the spelling mistake for the HoP coat
---
:cl:
- fix: Replaced the Head of Personell's Coat with the Head of Personnel's coat. We're not sure who the Head of Personell is, but godspeed you coatless soul.

Fix The Mispelling

---

Resources/Prototypes/Entities/Clothing/Eyes/glasses.yml
Resources/Prototypes/Loadouts/eyes.yml
Resources/Prototypes/Loadouts/mask.yml

Adds 3 new completely cosmetic goggles of the red, green, and purple variety, and adds them to loadouts. I have simply cloned the functional goggles and removed the functions from them, and put Budget at the end, because I think they'd look pretty cool. Also adds all the animal masks to loadouts.
---
:cl:
- add: Completely cosmetic goggles are now being sold for the low cost of 2 loadout points.
- add: We've realized we'd make more money selling the animal masks to crew instead of leaving them in maints.

Cosmetic Goggles and Animal Mask Loadout Options

---

Resources/ConfigPresets/Floofstation/floofstation.toml
Resources/Prototypes/Entities/Objects/Misc/spider_web.yml

Brings spider_web.yml to modern EE standards, and completely yeets an unused unloved config file. This will not have a CL, because it's bug busting. If this does not work, I might cry myself to sleep.
---

Content.Integration Works Again

---

Content.Shared/CCVar/CCVars.cs
Resources/Prototypes/Floof/Loadouts/outerClothing.yml
Resources/Prototypes/Loadouts/Jobs/science.yml

Adds the labcoat for everyone (the completely white one with no identifying colors), and increases the loadout points to 20. 
**(This NEEDS discussion unless you both agree on it)**
---
:cl:
- add: The lab coat is now available for everyone, because you can be a scientist without working in Epistemics.
- tweak: Loadout points have been increased from 14 to 20.

Loadout Point Increase And Labcoat For All

---

Content.Server/FloofStation/Traits/Components/CumProducerComponent.cs
Content.Server/FloofStation/Traits/Components/MilkProducerComponent.cs
Content.Server/FloofStation/Traits/LewdTraitSystem.cs
Resources/Prototypes/Floof/Traits/lewd.yml

This PR fixes the cum and milk generation so that it works properly now.
It also removes the "Floofstation" folder and instead uses "Floof" so now there is only one Floof folder.
It works with one or more traits as my testing has shown so far.
---
:cl:
- tweak: Tweaked starting max milk amount. 25u -> 50u
- tweak: Gave cumProducer a default SolutionName ("penis").
- tweak: Gave milkProducer a default SolutionName ("breasts").
- tweak: cumProducer takes less time to generate, but generates less per growth.
- tweak: milkProducer takes less time to generate, but generates less per growth.
- fix: Cum generation - When you eat something, your tank will refill and use hunger.
- fix: Milk generation - When you eat something, your tank will refill and use hunger.
- remove: Duplicate "Floof" …

Fixed Cum/Milk Generation

---

Resources/Prototypes/Floof/Entities/Clothing/Uniforms/misc.yml
Resources/Prototypes/Floof/Entities/Clothing/departmental_clothes.yml

Added the Skirt tag to all the thongs, and to the sex competition outfits, allowing Harpy's and other skirt-only species to wear them! This is a really simple fix, so I didn't add any media.
---
:cl:
- fix: harpies can now wear thongs, and the sex competition outfits! rejoice! :3

Add Skirt Tag to Thongs and Sex Comp Outfits

---

Resources/Prototypes/Floof/Recipes/Cooking/meal_recipes.yml

Rice pudding can now be made using 15 units of cream (10 milk 5 sugar) the old recipe still exists if you place them in to the microwave in different containers rather than mixing them
Description.
added a secondary recipe for rice pudding due to the sugar milk mixing into cream when all ingredients were mixed together
https://discord.com/channels/1255902263667331193/1274971717252415529
:cl:
- fix: Fixed Rice Pudding

Fix: Rice Pudding After Cream Change

---

Content.Shared/Teleportation/Systems/SharedPortalSystem.cs

Bandaid fix for leashed entities being dragged across the map when they or their puller enter a portal. Don't know why wizden hardcoded breaking pulling when entering a portal, but not breaking any other kind of joint...
No cl no fun

Break Leash Joints (and All Other Joints) when Entering a Portal

---

Resources/Prototypes/GameRules/events.yml
Resources/Prototypes/secret_weights.yml

This PR simply comments out the Zombie gamemode from appearing in Secret, and it comments out the Zombie outbreak that can happen at ANY time after an hour in survival and possibly extended. The gamemode still exists, but it wouldn't happen without admeme intervention. I believe this would be nice for the sake of this server in particular, as we're more on the roleplay side of things. Unclonable people are also just round removed when they become a zombie. Disaster roleplay could be "fun" but there are better ways to do that than zombies. 
---
:cl:
- remove: Zombies are gone from this sector, for now...

No Zombies For Now

---

Resources/Prototypes/game_presets.yml

Thieves can now appear in Survival and Extended (And Hellshift). That is literally all this does. This is an easy revert in case something goes wrong with this. I am also PRing this to EE.
---
:cl:
- tweak: Thieves have started appearing without Traitors...

Thieves Outside of Traitor

---

Content.Server/Atmos/EntitySystems/AtmosphereSystem.Commands.cs
Content.Server/Atmos/EntitySystems/AtmosphereSystem.Processing.cs

Fix Fixgridatmos Command (#27113)

---

Content.Shared/Floofstation/Traits/Components/FixtureDensityModifier.cs
Content.Shared/Floofstation/Traits/TraitStatModifierSystem.cs
Resources/Locale/en-US/Floof/traits/traits.ftl
Resources/Prototypes/Floof/Traits/physical.yml
Resources/Prototypes/Traits/physical.yml

Adds two new traits:
- Weakness - negative +5 point trait that halves your stamina pool, making you greately vulnerable to stunning attacks and fatigue
- Lightweight - positive -2 points trait that reduces your body density to 2/3, effectively reducing your mass to 2/3 of that of your peers.
Note: shoving and mass contests are completely broken right now. I will be submitting a PR to EE to fix them. This PR is standalone and will function without the future fix, although it will still benefit from it.
<p>
https://github.com/user-attachments/assets/6a99900d-e534-4ec5-81af-80a86bf30734
</p>
</details>
---
:cl:
- add: Added two new physical traits - weakness and lightweight

Weakness and Lightweight Traits

---

Resources/Prototypes/Entities/Objects/Fun/prizeticket.yml
Resources/Prototypes/Floof/Catalog/Cargo/cargo_fun.yml
Resources/Prototypes/Floof/Catalog/Fills/Crates/prizeball.yml

Adds a prize ball crate as a replacement for the plushie crate. It's 10 for 5k. This is the equivalent of buying the bulk carnival plushies instead of going to the carnival. I hope you like gacha games!
---
:cl:
- add: Prize Ball Crates can now be ordered from the market

Prize Ball Crate

---

Resources/Locale/en-US/Floof/traits/traits.ftl
Resources/Locale/en-US/traits/traits.ftl
Resources/Prototypes/Floof/Entities/Clothing/OuterClothing/wintercoats.yml

The default naming scheme is like, all lowercase for items I believe (and it also looks weird compared to the other items in the vendor). Also made Hollow Fangs capital, cause I'm weird and silly.

Fix Capitalization For Items/Trait

---

Content.Server/Body/Components/MetabolizerComponent.cs
Content.Server/Body/Systems/MetabolizerSystem.cs
Content.Server/Medical/CryoPodSystem.cs
Content.Shared/Chemistry/Components/Solution.cs
Content.Shared/Chemistry/EntitySystems/SharedSolutionContainerSystem.cs
Content.Shared/Medical/Cryogenics/CryoPodComponent.cs
Resources/Locale/en-US/Floof/reagents/meta/chemicals.ftl
Resources/Locale/en-US/Floof/reagents/meta/medicine.ftl
Resources/Locale/en-US/reagents/meta/medicine.ftl
Resources/Prototypes/Floof/Reagents/chemicals.yml
Resources/Prototypes/Floof/Reagents/medicine.yml
Resources/Prototypes/Floof/Recipes/Reactions/chemicals.yml
Resources/Prototypes/Floof/Recipes/Reactions/medicine.yml
Resources/Prototypes/Reagents/medicine.yml
Resources/Prototypes/Recipes/Reactions/medicine.yml
Resources/ServerInfo/Guidebook/Medical/Cryogenics.xml

Description.
added 2 intermidiate chems
- SalicylicAcid
- Formaldehyde
added 2 Cryo Chems
-Traumoxadone (Brute Damages)
-Stelloxadone (Tox Damages)
modified existing cryo chems to be more viable yet still balanced improved efficiency of cryo chambers
- Cryox only heals blood loss and air loss damage on a body, now useable after death
- Alox now also heals cold damage
- Doxa now uses Phalanximine not UnstableMutagen works after death twice as effective
- Oppo now uses Formaldehyde not Cognizine
updated cryo guide book to show all cryo chems
modified body metabolism
- the body no longer only metabolizes 2 chems at once but all chems in the system
- restrictive logic still somewhat in tact to prevent poison power gaming max 3 toxins
modified cryopods
- cryopods now split chems and inject …

Cryo Overhaul

---

Content.Shared/Customization/Systems/CharacterRequirements.Logic.cs
Content.Shared/Customization/Systems/CharacterRequirementsSystem.cs

Cherry-picks https://github.com/Simple-Station/Einstein-Engines/pull/891
:cl:
- fix: Hotfixed some job requirements with logical OR.

Cherry-Pick "Fix Logic Requirements Not Checking Inversion"

---

Content.Shared/Floofstation/Leash/Components/LeashComponent.cs
Content.Shared/Floofstation/Leash/LeashSystem.cs
Resources/Prototypes/Entities/Mobs/NPCs/silicon.yml
Resources/Prototypes/Floof/Entities/Objects/Tools/leash.yml

This:
- Effectively disables client-side prediction for leash joints (by setting their maximum distance to +inf on the client side), thus fixing the visual glitches happening client-side  when you are dragged via a leash.
- Makes it so that leash joints are re-created if they are broken illegally (mostly by the ss14 physics engine when an entity enters a container or such), which allows leashed entities to be in containers and more, as well as preserves leashes during FTL.
- Tweaks some parameters of the existing leashes (normal leash length reduced from 3.5m to 3m, maxDistance was adjusted on all leashes to be ~double of their lengths)
- Adds leash anchors to bots (medibot, janibot, mimebot, two clownbots), for obvious reasons.
- Removes some redundant code.
---
:cl:
- add: You can now …

Leash Tweaks & Fixes

---

Content.Shared/Floofstation/Leash/LeashSystem.cs

I did an oopsie and messed up the operation order, causing the leash to immediately get re-created after being removed, even if the latter was done manually.
:cl:
- fix: Leashes should now be properly removable.

Hotfix Leashes Being Unremovable

---

Resources/Prototypes/Entities/Markers/Spawners/Random/techboard.yml

This PR attempts to make R&D Servers more common to alleviate issues with Epi. It ALSO adds back shuttle boards to the tech board loot pool.
This reduces the amount of dice rolls for R&D servers by one, hopefully making it easier to find servers for epi whilst I work on reworking the servers overall.
---
:cl:
- add: Shuttle Console Boards added to the Tech Board loot pool.
- tweak: R&D Server boards are now common finds.

Make R&D Servers More Common

---

Content.Shared/Floofstation/Leash/Components/LeashComponent.cs
Content.Shared/Floofstation/Leash/LeashSystem.cs

So uhhh the last fix introduced a severe bug that caused FTL to fail if the FTLing shuttle contained an entity who had a leash attached to themselves in their inventory (sorry :sob:). This reworks the system to fix that and more bugs.
Leash joints can now be created/disposed of dynamically throughout the lifespan of a leash, without forcing the removal of the latter. This is used to prevent the physics engine from creating a joint that would connect an entity with itself (which is exactly what happens when you put a leash attached to yourself in your inventory.
This also indirectly fixes the issue with leashes breaking when put in the inventory of the leashed person, and allows a person to attach a leash to themselves, and ensures that leashes break when going through portals, unless the …

Another Leash Fix

---

Resources/Prototypes/Announcers/!randomAnnouncers.yml

This re-adds the NEIL announcer with a 50% chance to appear in a shift, as it is the only announcer that is somewhat completed upstream.
This is a single-line YML change.
:cl:
- tweak: The NEIL announcer can once again appear in a shift.

Re-Add the NEIL Announcer

---

Resources/Locale/en-US/Floof/loadouts/categories.ftl
Resources/Locale/en-US/Floof/loadouts/itemgroups.ftl
Resources/Prototypes/Floof/CharacterItemGroups/funGroup.yml
Resources/Prototypes/Floof/Entities/Objects/Tools/leash.yml
Resources/Prototypes/Floof/Loadouts/Categories/categories.yml
Resources/Prototypes/Floof/Loadouts/items.yml
Resources/Prototypes/Floof/Loadouts/itemsLewd.yml
Resources/Prototypes/Floof/Loadouts/neck.yml

- Adds two leashes and a remote signaler to the Items loadout category
- Adds a shock collar to the Neck loadout category
- Adds a new Lewd loadout category, containing all lewd items featured by floof (it is going to be made a subcategory of Items after EE splits Items into separate subcategories [just a week away])
<p>
</p>
</details>
---
:cl:
- add: Loadouts have been expanded with leashes, remote signalers, shock collars, and a wide variety of lewd items.

Silly Loadouts

---

Content.Server/Disposal/Unit/EntitySystems/DisposableSystem.cs

This PR fixes an issue with disposal pipes that lead into space. The ejection would use the transform of the map instead of the one from the grid and throw into the wrong direction. 
Another issue this fixes is with disposal bends which would take direction from a previous pipe instead of the current one.
:cl:
- fix: Fix the disposal pipe ejection to space and after pipe bends.

Fix Disposal Pipes Ejection

---

Resources/Prototypes/Reagents/medicine.yml

Adds a 10 degree buffer to leporazine's temperature effects so it doesn't wildly heat and cool you down in a loop.
Leporazine is a drug meant for stabilization of a body's temperature, but it has a tendency to heat someone way higher, and when cooling the body, it would trigger the heating effect of the chemical again, looping until the chemicals effect ends, where it's likely that you're left on a high temperature. Adding this buffer allows you to stay around 298k temp without being shocked all the way to 344k constantly every time you are cooled back down from lepo.
---
---
:cl: Xavier
- tweak: Lepo now has a 10 degree buffer between it's heating and cooling effect to prevent looping temperature shocks.

Fixes Leporazine Temperature Shock

---

Resources/Prototypes/GameRules/roundstart.yml

Reduces the max amount of traitors that can spawn in a round.
---
:cl:
- tweak: Reduced the max amount of traitors in a shift.

Reducing Antag Amount for Security Balance

---

Resources/Textures/Shaders/ethereal.swsl

This should fix a regression introduced by #244 that prevents Floofstation from starting when Compatibility Mode is on in the launcher. The launch fail is due to type issues in the shader code. The PR does not change the meaning of the code, just fixes the type issues.
```
ERROR: 0:263: '*' : wrong operand types - no operation '*' exists that takes a left-hand operand of type 'const int' and a right operand of type 'const float' (or there is no acceptable conversion)
ERROR: 0:263: '+' : wrong operand types - no operation '+' exists that takes a left-hand operand of type 'const float' and a right operand of type 'const int' (or there is no acceptable conversion)
ERROR: 0:266: 'assign' : cannot convert from 'const int' to 'highp float'
```
:cl:
- fix: Fixed regression bug that prevents …

Fix ethereal.swsl not compiling in Compatibility Mode

---

Content.Server/Shadowkin/EtherealStunItemSystem.cs
Content.Shared/Shadowkin/EtherealComponent.cs
Resources/Prototypes/Floof/Entities/Structures/shadowkin.yml

This is an fix for the Dark Portal being able to be yeeted into realspace when stunned by a bluespace crystal.
---
:cl:
- fix: Dark Portals cannot be yeeted out of Ethereal by bluespace crystal anymore.

Dark Portal Etheral Fix

---

Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Resources/Prototypes/Floof/Recipes/Lathes/security.yml

as you know there isn't a way to get more 45 pistol mags for weapons like the N1984  this would allow sec to make empty and then regular mags for the pistol. since revolvers have speed loaders. and all the other guns (but like shotguns even then there is a mag shotgun) can be made why cant this one?
<p>
</p>
</details>
---
:cl:
- add: add .45 pistol mag to the Sec fab

add the 45 mag to the sec fab

---

Resources/Prototypes/Recipes/Reactions/medicine.yml

Description.
upstream merge overwrote oppo recipe, this is returning it to the Formaldehyde recipe
---
:cl:
- fix: Changed the Opporizadone recipe to use Formaldehyde again.

returning it to the Formaldehyde recipe for Oppo

---

Resources/Prototypes/Body/Prototypes/ipc.yml
Resources/Prototypes/Body/Prototypes/shadowkin.yml
Resources/Prototypes/DeltaV/Body/Prototypes/harpy.yml
Resources/Prototypes/DeltaV/Body/Prototypes/vulpkanin.yml
Resources/Prototypes/Nyanotrasen/Entities/Body/Prototypes/arachne.yml
Resources/Prototypes/Nyanotrasen/Entities/Body/Prototypes/felinid.yml

Fixes that weird swapped hands visual bug on the HUD by swapping the actual hands on the species.
This should probably go to EE but I don't really know how to be honest xwx
---
<p>
</p>
</details>
---
:cl:
- fix: fixed the backwards hand/description bug on the HUD for some species by swapping the hands :3

Swapped Hands HUD Fix

---

Resources/Prototypes/Catalog/Cargo/cargo_hardsuits.yml

This was planned to be removed, i commented the wrong suit out, this fixes it.
---
:cl:
- remove: Removed the blue nukie suits.

Remove Blue Nukie Suit From Cargo

---

Resources/Prototypes/Catalog/uplink_catalog.yml
Resources/Prototypes/Store/presets.yml

Moving all chems into Misc where they used to be and Deception into utility where they used to be as well. 
---
:cl:
- tweak: Syndicate uplink misc and ultility trees 
- remove: Removed unused categories that were not set up.

Sydicate Uplink Fixes

---

Resources/Prototypes/DeltaV/Entities/Clothing/Eyes/hud.yml

Adds the VisionCorrection component back to prescription HUDs (sechud/medhud)
---
:cl:
- fix: Prescription Lenses re-added to prescription MedHUDs and prescription SecHUDs.

Prescription HUDs Fix

---

Resources/Prototypes/Traits/physical.yml

Makes it so the bionic arm can't open powered doors.
Gladiators can't have bionics.
---
:cl:
- fix: Gladiators can no longer have bionics.
- tweak: Bionic arm cannot opened powered doors. Cost reduced to 6 instead of 8.

Bionic Changes and Fixes

---

Resources/Prototypes/Entities/Objects/Consumable/Smokeables/Cigarettes/cigarette.yml

Per request, this change removes the nicotine from Interdynes but replaces it with Iron and Dylovene.
---
:cl:
- tweak: Removed nicotine from Interdynes and replaced it with iron and dylovene.

Herbals Don't Contain Nicotine

---

Resources/Prototypes/Entities/Mobs/NPCs/animals.yml

Why is it that Slime players can speak to Slimes, Ratania players can speak to Ratkings(In mouse), rats and mice, Moffs can speak to Mothroach BUT YET Aranchid can't speak to spiders at all?  How many Aranchid players do you ever see? (there isn't a lot) This would allow Players to talk to Spider Mobs like  Shiva, Clown spiders, Tarantulas and Space spiders  (and REALLY should be able to talk to Laika and others dogs since Vulpkins are a canine-like being )
---
---
:cl:
- tweak: Aranchids can now speak to shiva and other spiders

Allows Aranchid to Talk to Spiders

---

Content.Server/StationEvents/Events/PirateRadioSpawnRule.cs

You are now free from the burden of this infamous heisentest.
Also I can PR the engine updates with no issue, if you'd like? Not sure if that's something y'all would want, but it wouldn't be hard. The engine update includes the arrivals visuals PR, so, might be good to get that lmao.

Fix PirateRadio Heisentest

---

Resources/Prototypes/Maps/glacier.yml

This changes the evac shuttle on glacier from the default, small shuttle, meant for tiny stations; to the emergency shuttle that is used on Shoko, which is way more appropriately sized for the stations population. 
Thats it. 
---
:cl: Crow
- tweak: Adjusted Glacier evac shuttle

Glacier Emergency Shuttle Replacement - NTES Delta (Shoko Evac)

---

Content.Server/Chat/Systems/ChatSystem.cs
Content.Server/Polymorph/Systems/PolymorphSystem.cs
Content.Shared/Polymorph/PolymorphPrototype.cs
Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
Resources/Prototypes/Entities/Mobs/NPCs/glimmer_creatures.yml
Resources/Prototypes/Entities/Mobs/NPCs/revenant.yml
Resources/Prototypes/Entities/Objects/Devices/pda.yml
Resources/Prototypes/Entities/Objects/Specific/Robotics/mmi.yml
Resources/Prototypes/Language/animal.yml
Resources/Prototypes/Nyanotrasen/Entities/Objects/Specific/Mail/base_mail.yml

Cherry-picks https://github.com/Simple-Station/Einstein-Engines/pull/1223
Because the upstream merge is a whole week away (or whenever I get the motivation to debug the issues with it)
Original body:
<details><summary><h1>Click to expand</h1></summary>
1. Adds languages to... penguins, cockroaches, snakes, mmis, pdas, mail packages. Positronic brains now only speak/understand the borg language.
2. Adds an explicitly defined universal language to revenants and wisps
3. Makes polymorphs copy over a list of components defined in the polymorph proto, thus copying languages and grammar of the original entity to its polymorphed version.
<p>
</p>
:cl:
- tweak: Added languages to certain entities that lacked them, including MMIs and positronic brains.
- add: Polymorphing into another entity now …

Cherry-Pick «Some Language Fixes»

---

Resources/Prototypes/CharacterItemGroups/serviceGroups.yml
Resources/Prototypes/Floof/Loadouts/Jobs/service.yml

Adds the .20 rifle rubber box to the Bartender's loadout for the Argenti.
---
:cl:
- add: .20 Rifle Rubber Ammo Box to Bartender loadout.

Add .20 Rifle Rubber Box to Bartender Loadout

---

Resources/Prototypes/Mood/genericNegativeEffects.yml
Resources/Prototypes/Mood/genericPositiveEffects.yml

For ages players with the sanguine trait could completely ignore hunger and dehydration without suffering any negative effects (besides being unable to regenerate blood), while players with saturnine could never escape the hook of depression. This nerfs both of those traits to make them less powergamey and more playable, respectively.
- Sanguine mood buff has been reduced from 15 to 8 (being completely starved and dehydrated at the same time only gives you -14)
- Saturnine mood debuff has been reduced from -20 to -12.
:cl:
- tweak: The effects of the Sanguine and Saturnine traits have been made significantly weaker.

Mood Traits Nerf

---

Content.Client/Clothing/ClientClothingSystem.cs
Resources/Prototypes/DeltaV/Entities/Mobs/Species/rodentia.yml
Resources/Prototypes/DeltaV/Entities/Mobs/Species/vulpkanin.yml
Resources/Prototypes/Entities/Mobs/Species/arachne.yml
Resources/Prototypes/Entities/Mobs/Species/base.yml
Resources/Prototypes/Entities/Mobs/Species/diona.yml
Resources/Prototypes/Entities/Mobs/Species/reptilian.yml

This PR removes females displacement and port a tiny fix.
---
:cl: FoxxoTrystan
- remove: Removed females displacement to avoid a bug.

Female Displacement Disabled

---

Resources/Prototypes/Loadouts/Jobs/engineering.yml
Resources/Prototypes/Loadouts/Jobs/security.yml

Medical department, in its current state, allows senior physician uniform to be worn by all roles excluding the intern role. See below image.
This PR expands this logic to both security and engineering department, which in the current state, restricts the senior uniforms to just the basic Security Officer or Station Engineer respectively. This PR allows Atmosians, CE, HoS, Warden, and Detective to equip their departmental senior uniforms in the loadout menu. 
:cl: Crow
- tweak: Expanded which jobs can wear senior uniforms

Senior Uniforms to More Jobs

---

Content.Server/Medical/DefibrillatorSystem.cs
Content.Server/Traits/Assorted/UnrevivableComponent.cs
Resources/Locale/en-US/medical/components/defibrillator.ftl
Resources/Locale/en-US/traits/traits.ftl
Resources/Prototypes/Traits/disabilities.yml

Adds the unrevivable trait, ported from https://github.com/space-wizards/space-station-14/pull/24226
Should preserve compatibility with wizden/ee.
<p>
</p>
</details>
:cl:
- add: Added the "Unrevivable" trait for those who like to live on the edge.

Unrevivable Trait

---

Content.Server/Chemistry/TileReactions/CleanTileReaction.cs
Content.Server/FootPrint/FootPrintsSystem.cs
Content.Shared/Footprint/FootPrintsComponent.cs

- Makes it so that CleanTileReaction (space cleaner, water, bleach) clean footprints as well as puddles
- Makes it so that flying (slipping or otherwise) entities do not leave footprints
- Adds some missing floof edit comments
<p>
https://github.com/user-attachments/assets/7e931986-3789-4240-ba02-03941e66d3f8
</p>
</details>
:cl:
- fix: Space cleaner can now clean footprints, and mobs won't leave footprints while flying.

Footprints Fixes

---

Content.Server/FloofStation/GameTicking/StationEventCondition.cs
Content.Server/FloofStation/GameTicking/StationEventConditions.Players.cs
Content.Server/FloofStation/GameTicking/StationEventConditions.Utility.cs
Content.Server/StationEvents/Components/StationEventComponent.cs
Content.Server/StationEvents/EventManagerSystem.cs
Resources/Prototypes/Floof/Gamerules/base.yml
Resources/Prototypes/GameRules/events.yml

Implements some basic framework for customizable event conditions (currently featuring 3 types of conditions: job count condition, departament count condition, and complex condition - boolean and/or), and adds:
- A condition for at least 2 security players for most midround antags
- A condition for at least 2 enineering players for meteor swarms
- A condition for at least 1 epistemics player for random anomaly spawn
The existing conditions determine a player's job by first performing an inverse lookup by their ID title, and then, if it fails, checking the job they took when joining the station (dictated by the JobComponent on their mind. It's extremely dumb, I know, but neither ID cards nor player entities actually store your current job)
This needs further testing and adjustments. …

Event Conditions

---

Resources/Prototypes/Entities/Mobs/Species/base.yml

*Sighs*. Vulps, felinids, and probably other nyano/floof species lacked the footprints comp.
This adds the footprints comp to the base species proto. I will need to test this later because this was done via github web interface and I cannot guarantee it won't break something immediately.
<p>
None, needs testing.
</p>
</details>
:cl:
- fix: Vulpkanins and other species should now properly leave footprints.

Fix some Species Not Leaving Footprints

---

Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Boxes/rifle.yml
Resources/Prototypes/Floof/Loadouts/Jobs/service.yml

This PR fixes the ammo in the .20 Rifle Box to be rubbers instead of practice rounds.
It also adds the speedloader for the Argenti to the Bartender's loadout.
Note the speedloader currently can be chosen even without the Argenti. This will be updated later on.
---
:cl:
- add: .20 Rifle Speedloader to Bartenders
- fix: .20 Rubber Rifle Box gives the correct ammo type.

Fix .20 Rifle Rubber Box and Added Rubber .20 Speedloader for Bartenders.

---

Content.Server/StationEvents/Components/VentCrittersRuleComponent.cs
Content.Server/StationEvents/Events/StationEventSystem.cs
Content.Server/StationEvents/Events/VentCrittersRule.cs
Resources/Locale/en-US/station-events/events/vent-critters.ftl
Resources/Prototypes/DeltaV/GameRules/events.yml
Resources/Prototypes/Floof/Gamerules/Events.yml
Resources/Prototypes/GameRules/base.yml
Resources/Prototypes/GameRules/events.yml

Adds a double random delay to the vent critters rule, as well as optional sounds and popups. Also prevents the gamerule from spawning mobs on welded vents, implements the framework for delayed spawn for use in other entity systems, fixes some ftl problems (including the missing announcement for spider clowns)
<p>
https://github.com/user-attachments/assets/e31933ea-6c41-488e-8091-58b42e040ee6
</p>
</details>
:cl:
- add: Vent critters will no longer spawn immediately after being announced, and their appearance is now accompanied by audiovisual warnings appearing up to 6 seconds ahead of their spawn.

Better Vent Critters

---

Content.Server/Fluids/EntitySystems/AbsorbentSystem.Footprints.cs
Content.Server/Fluids/EntitySystems/AbsorbentSystem.cs
Content.Server/FootPrint/FootPrintsSystem.cs
Content.Shared/Fluids/AbsorbentComponent.cs
Resources/Prototypes/Entities/Effects/puddle.yml
Resources/Prototypes/Entities/Objects/Specific/Janitorial/janitor.yml

- Gives absorbents an AOE effect. Regular absorbents (dump rags and cleanbots) clean footprints in a 0.2m radius, up to 25 footprints. Mops clean in a 0.45m radius, and advanced mops - in a 0.75m radius.
- Adds the missing solution components to footprints. They can now be properly examined and can be drawn from with a syringe (potassium footprints my beloathed).
- Makes it so that the "dragging" prints are applied based on whether the entity is laying down rather than whether it's alive.
<p>
https://github.com/user-attachments/assets/7601f45e-51e9-41dc-b84b-a9273c1ff38a
https://github.com/user-attachments/assets/2674c872-d2d4-489d-9419-767b7eb3dd89
</p>
</details>
:cl:
- add: Mops, damp rags, and cleanbots now have area-of-effect cleaning, …

Even Better Footprints

---

Resources/Prototypes/Entities/Clothing/Eyes/glasses.yml
Resources/Prototypes/tags.yml

Added the tag "GlassesNearsight" to the tag list in tags.yml and tagged the glasses prototype with it. The crafting graph for prescription HUDs expects this tag.
The construction graph for the prescription versions of the sec and med HUDs requires an item with the tag "GlassesNearsight". This tag was not on the glasses prototype nor in the list of tags. When attempting to build a prescription HUD with the appropriate HUD, cables, and glasses, but not the glue, the local server would encounter a hard error that closed it. Other combinations were not tested.
---
---
:cl: sprkl
- fix: Fixed a crash that occurred while trying to build prescription huds.

Prescription HUD Construction Crash Fix

---

Content.Client/Effects/ColorFlashEffectSystem.cs
Content.Server/Carrying/CarryingSystem.cs
Content.Server/FootPrint/FootPrintsSystem.cs
Content.Server/FootPrint/PuddleFootPrintsSystem.cs
Content.Server/Instruments/InstrumentSystem.cs
Content.Server/Nyanotrasen/Kitchen/EntitySystems/DeepFryerSystem.Storage.cs
Content.Server/Nyanotrasen/Kitchen/EntitySystems/DeepFryerSystem.cs
Content.Shared/Floofstation/Leash/LeashSystem.cs
Content.Shared/Footprint/FootPrintsComponent.cs
Content.Shared/Footprint/PuddleFootPrintsComponent.cs
Content.Shared/Standing/StandingStateSystem.cs
Content.Shared/Tools/Systems/SharedToolSystem.Welder.cs
Resources/Locale/en-US/Floof/leash/leash.ftl
Resources/Prototypes/Entities/Objects/Decoration/ashtray.yml
Resources/Prototypes/Entities/Objects/Specific/Medical/morgue.yml
Resources/Prototypes/Entities/Structures/Furniture/Tables/tables.yml

Did a pass to fix most bugs known to me.
Codewise changes:
- Rewrote the footprints system, mostly. The system now precisely keeps tracks of reagents collected from puddles, which prevents reagent duping or reagent vanishing (both of which were possible with the old system), and also allows to transfer more than 1 reagent at once, to transfer water with footprints, and (oh god) mix water with potassium on YOUR OWN FEET
- Leash system: fixed the bug that allowed you to set the length of a leash regardless of whether you can interact with it, and added additional examination text and popups.
- Standing state system: Fixed laying down near a table allowing you to bypass any windoors or walls blocking access to the said table.
- Carrying system: carrying an entity standing beside a table …

Mass Bug Fixes

---

Resources/Maps/Floof/kettle.yml
Resources/Maps/Floof/lighthouse.yml
Resources/Maps/Floof/radstation.yml
Resources/Prototypes/Maps/Pools/default.yml

Additional community requested changes for Kettle & Rad station
Added various things to all stations that the community requested. Mostly a lot of beacons for the station maps and warp points.
Map Specific Changes:
Kettle:
- added missing warp poitns
- added missing station beacons
- changed solars to have some broken so engineering will need to repair them
- added more station maps
- added arrivals shuttle ETA screen
- added evac shuttle ETA screen
- extended salvages dock to allow for them to dock to the station easier and to allow the logi shuttle to fit into the logi shuttle docking bay
- added justice key to service telecoms
- added a station anchor
Rad:
- renamed all substations, smes faxes
- moved vault from its old location to the portal room that was above epi
- changed the old …

Map Reworks Kettle and Rad

---

Content.Server/DeltaV/ParadoxAnomaly/Systems/ParadoxAnomalySystem.cs
Resources/Locale/en-US/Blep/consent.ftl
Resources/Prototypes/consent.yml

Adds an opt-out for targets of the Paradox Anomaly ghost role through the consent menu.
:cl:
- add: Paradox Anomaly clones of your character can be disabled through the consent preferences menu.

Paradox Anomaly Opt-Out Consent Toggle

---

Resources/Prototypes/Entities/Objects/Specific/Robotics/borg_modules.yml
Resources/Prototypes/Floof/Entities/Objects/Weapons/borgmodules.yml

commit
Salvage borg had no melee weapon and couldn't really used the pka due to the weapon angel angel-wielding requirement 
this PR gives them a Survival knife (as told by floor)
---
:cl:
- tweak: SESWC tinkered with the salvage borg PKA module and taped a knife to its other arm.

Pka Salvage Borg Changes 

---

Resources/Prototypes/Floof/Entities/Mobs/Cyborgs/quadborg.yml
Resources/Prototypes/Floof/Entities/Objects/Specific/Robotics/Borgmodules.yml
Resources/Prototypes/Recipes/Construction/Graphs/tools/BorgModules.yml
Resources/Prototypes/Recipes/Construction/tools.yml

Disables Investigation crafting due to deletion bug 
---
---
:cl:
-remove: removed investigation construction.

Emergency Hotfix

---

Content.Server/FloofStation/Speech/Components/DrunkardAccentComponent.cs
Content.Server/FloofStation/Speech/EntitySystems/DrunkardAccentSystem.cs
Resources/Locale/en-US/Floof/traits/traits.ftl
Resources/Prototypes/CharacterItemGroups/languageGroups.yml
Resources/Prototypes/Floof/Traits/neutral.yml

Adds a "drunkard accent", a trait that makes a character's speech slurred like they're drunk.
There are a few alcoholic characters on Floof that would benefit from being "constantly drunk" without the actual status effect. This could be a good effect for other characters that have a speech impediment.
This uses a modified version of `SlurredSystem`'s `Accentuate` for the trait with hardcoded values and removing the burping and "huh" additions. The functionality *could* be extracted into a static method, however it would require changing code in non-Floof code when this works perfectly fine; reducing changes to the codebase is preferable.
If the character is drunk past a certain point, the `SlurredSpeech` effect will take precedence over `DrunkardAccent`.
:cl:
- add: Added a "drunkard …

Drunkard Accent

---

Content.Server/Xenoarchaeology/Equipment/Components/ArtifactAnalyzerComponent.cs
Resources/Prototypes/Entities/Structures/Machines/artifact_analyzer.yml

This makes ExtractRatio property of artifact analyzers (the amount of points needed to raise 1 milipsi of glimmer) a DataField, and changes that property of MachineArtifactAnalyzer to be 2.5 times higher than the default (1000 instead of 400 points per 1 milipsi).
This should make xenoarch more of a viable research method, because as of now anomalies are the go-to due to their incredibly low glimmer generation compared to that of xenoarch.
:cl:
- tweak: Artifact extractions should now generate 2.5 times less glimmer than before.

Increase Artifact Analyzer's Point-to-Glimmer Ratio

---

Resources/Prototypes/Traits/disabilities.yml

Adds incompatibility to ensure that someone cannot take negative visual traits while having cyber-eyes systems, and likewise cannot take redundant negative visual traits.
---
<p>
</p>
</details>
---
:cl:
- fix: Made Photophobia, Blindness, Nearsightedness, and Cyber-eyes mutually exclusive.

Make Visual Disabilities and Cybereyes Mutually Exclusive

---

Resources/Prototypes/Floof/Catalog/Cargo/cargo_misc.yml
Resources/Prototypes/Floof/Catalog/Fills/Crates/cleannade.yml

adds the ability to Buy JUST clean grenades for when the station is extremely dirty
get it to work 
:cl:
- add: Clean grenades crate buyable from cargo

Space Cleaner Grenade Crate 

---

Content.Shared/Cuffs/SharedCuffableSystem.cs

This PR fixes a bug regarding the Cyborg Zipties, when an ent was cuffed, the new ziptie was not "used", this changes it.
In general in my head i should not have used cuffsystem to make this, but right now this will work and i think its should be changed.
---
:cl: FoxxoTrystan
- fix: Fixed cyborg zipties being unable to be removed.

Cyborg Zipties Patch

---

Resources/Prototypes/Entities/Mobs/NPCs/gladiabot.yml
Resources/Prototypes/InventoryTemplates/gladiabot_inventory_template.yml

This adds an inventory template for a Gladiabot and allows it to wear hats.
This makes it easier to see which bot is which in a fight, allowing people to place bets on the winner!
There is no way to force an orientation for a hat that I know of, but it still looks OK if the hat is sideways
---
---
<p>
</p>
</details>
---
:cl: Timfa
- tweak: Allowed Gladiabots to wear hats!

Allow Gladiabots to Wear Hats

---

Resources/Prototypes/Catalog/VendingMachines/Inventories/salvage.yml

most stations are equipt with 3-4 salvagers and most salvagers already just go to get the saw to saw off the PKA to make the sawn off version because of the firing rate. this is really just a time saver quality of life thing 
Replaces two regulars with sawn-off versions 
<p>
</p>
</details>
---
:cl:
- tweak: There is now 2 sawn-off pka and 2 regular pka in the vendors instead of 4 regular pka's

Converts 2 Regular Pkas to 2 Sawn Off Pka in the Vendor

---

Resources/Prototypes/Catalog/uplink_catalog.yml

I go banned
It causes extreme Destruction on the station, items of this nature was already removed (zombie bundle, china lake)
real reason is I got banned for using a Beacon so I want to prevent other people from getting banned
Description.
:cl:
- remove: Removed the singulo beacon from the uplink.

Removes the Beacon From the Uplink

---

Resources/Prototypes/Entities/Objects/Fun/prizeticket.yml
Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Resources/Prototypes/Recipes/Lathes/prizecounter.yml

adds that shitty plushie to the prize
adds that shitty plushie to the prize counter
:cl:
- tweak: Added the girl failure plushie to the prize counter and prize balls.

add plushie to the prize

---

Resources/Prototypes/Entities/Mobs/Customization/Markings/moth.yml

Moth wings didnt show up in game, due to them beeing on a wing layer instead of tail, fixed the issue while keeping them in the wings category
---
n/a
---
:cl:
- fix: Made the moth wings appiear again

Moth Wings Quick Fix

---

Content.IntegrationTests/Tests/PostMapInitTest.cs
Resources/Maps/Floof/Shuttles/cargo_fland.yml
Resources/Prototypes/Maps/Pools/default.yml
Resources/Prototypes/Maps/fland.yml

Add Fland as a playable high pop map. Fland is a station mostly used on wizden that is meant for a large amount of crew. It has much larger departments to accommodate for the player count. This is a more engineering and logi focused station. Engineering has every type of power generation at their disposal but more importantly, engineering also has a shuttle build bay (directly below arrivals for anyone not familiar with the map.) This allows them to construct shuttle in a space place and with team work from logi and epi mulitple shuttles can be produced in a single shift. On top of that, it allows for an admin event for engineering to build a shuttle for centcom in order to have centcom "sell it" and provide logistics with money in return for its completion.
Security on this station is …

Map Addition Fland

---

Content.Server/Pinpointer/NavMapSystem.cs

Cherry-picks https://github.com/space-wizards/space-station-14/pull/28518 from WizDen to fix station beacons disappearing on grid split. This has not been tested, should test it before merging.
:cl: Errant-4
- fix: Map labels no longer suddenly disappear for the rest of the round.

Beacons no longer glitch off on grid split (WizardsDen#28518)

---

Resources/Prototypes/Body/Parts/generic.yml

Copy/paste error causing bio-synthetic left lefts to expect right feet as children.
---
:cl:
- fix: Bio-synthetic left legs now properly expect and allow a left foot to be attached.

Biosynthetic Left Leg Fix

---

Resources/Prototypes/Floof/Body/Parts/resomi.yml
Resources/Prototypes/Floof/Body/Prototypes/resomi.yml

Copying the templating from the vulpkanin and human definitions to make sure resomi body parts fit in the new medical system. Now you can detach their limbs and actually attach something back in their place.
Note/known visual bug: attaching non-resomi limbs, including the utility limbs, causes them to visually float in place. This should be fixed at some point. They work, they just aren't visually attached to the sprite.
---
:cl:
- fix: Resomi now can have limbs reattached after having them removed.

Update Resomi body and parts definition to follow surgery update specifications

---

Resources/Prototypes/Atmospherics/thresholds.yml

Increases the default CO2 danger threshold on air sensor components to 1%. The warning threshold is changed to 0.5% (automatically calculated as half of the danger threshold).
This will reduce the currently-common occurance of nuisance alarms, which currently distract atmospherics attention and train people to ignore the air alarms, degrading their purpose. This is an especially large problem with the addition of the atmospheric alert computer.
I have extensively tested the danger of CO2, and determined 1.2% to be the point at which it starts to become potentially dangerous. The danger level of 1% stands off slightly short of this and ensures that firelocks will come down in the event of any dangerous concentration of CO2. The air alarm warnings will also trigger significantly in advance …

Increase CO2 sensor danger threshold to 1%

---

Resources/Prototypes/Floof/Catalog/Fills/Crates/medical.yml
Resources/Prototypes/Floof/Entities/Objects/Devices/flatpack.yml
Resources/Prototypes/Floof/Entities/Objects/Specific/Medical/surgery.yml

As I was testing all of these surgery bugs I often found myself spawning in the same items over and over again every time I needed to reload the instance. I figured not only would it be easier on myself to make a crate prototype, but it could also serve as an ERT Medical option. Includes:
- a souped up medical multitool (because ERT get the fancy tools)
- sterile mask and nitrile glove boxes
- a general anesthetic tank
- a medical breath mask, 
- flatpacks for a medical biofabricator and an operating table
- a multitool to unpack the flatpacks
- 300 biomass to print up to 30 body parts
---
:cl:
ADMIN:
- add: Added an ERT surgical tools crate, which includes new items such as an admeme medical multitool and flatpacks for the med biofab and operating tables.

ERT/Testing Surgical Tool Crate

---

Resources/Prototypes/Floof/Catalog/Cargo/cargo_atmospherics.yml
Resources/Prototypes/Floof/Entities/Structures/Storage/Canisters/gas_canisters.yml

For how necessary N2O/O2 mix is for medbay now, it's more difficult to come by than it should be. I've made canisters of pre-mixed N2O/O2 in the same ratio that the robovend canisters are at, labeled them "general anesthesia canister" to differentiate them from normal nitrous oxide, and also made a logistics orders so we can actually get them reasonably. In both standard temp and pressure and liquid varieties.
---
:cl:
- add: General anesthesia and Liquid general anesthesia canisters can now be purchased from Logistics.

General anesthesia canisters and associated cargo order

---

Content.Server/Atmos/EntitySystems/BarotraumaSystem.cs
Content.Shared/Body/Part/BodyPartComponent.cs
Content.Shared/Body/Systems/SharedBodySystem.Targeting.cs

This increases the default part severing threshold (the amount of damage it takes to severe a part) from 90 to 300 damage, increases the disability threshold (the amount of damage to DISABLE a part without severing it) from 90 to 100, weakens the damage multiplier of TargetBodyPart.All (damage dealt by things like fire that affect your whole body) from 0.5x to 0.1x, and decreases barotrauma damage to parts to only 40% (so the body will receive most of the damage, while its parts will receive very little).
Also spent some time silently crying from how bad the body part damage code is.
<p>
Part severing:
https://github.com/user-attachments/assets/4da55afa-ea75-4d6c-b9d3-95be2dd2f66e
</p>
</details>
:cl:
- tweak: Made it overall harder to severe …

Weaken the effects of damage on body parts

---

Resources/Prototypes/DeltaV/Guidebook/species.yml
Resources/Prototypes/Guidebook/species.yml
Resources/ServerInfo/Guidebook/Mobs/DeltaV/Felinid.xml
Resources/ServerInfo/Guidebook/Mobs/DeltaV/Harpy.xml
Resources/ServerInfo/Guidebook/Mobs/DeltaV/Oni.xml
Resources/ServerInfo/Guidebook/Mobs/DeltaV/Vulpkanin.xml
Resources/ServerInfo/Guidebook/Mobs/Dwarf.xml
Resources/ServerInfo/Guidebook/Mobs/Species.xml

Ports https://github.com/DeltaV-Station/Delta-v/pull/1174 with some minor tweaks for Floof. That PR added guidebook entries for Vulpkanin, Felinid, Harpy, and Oni based on their wiki.
Primary differences:
Floof already has a Harpy guidebook entry so I commented out the Harpy definition from DV
This PR adds a note to Dwarf saying it's disabled - modified it to say disabled on Floofstation (vice DV)
Additional note:
MobFelinid, MobFelinidDummy, and MobOniDummy seem to be broken visually, but I believe fixing that should be outside the scope of this PR/commit.
---
---
<p>
</p>
</details>
---
:cl:
- add: Vulpkanin, Felinid, and Oni guidebook entries from Delta-V

Add Delta-V species guidebook entries

---

Content.Client/Buckle/BuckleSystem.cs
Content.Shared/Body/Systems/SharedBodySystem.Body.cs
Content.Shared/Standing/SharedLayingDownSystem.cs

- Fixed the bug where borgs couldn't stand up after going crit (or any entity with standing state and body, but no limbs)
- Fixed the bug where buckle layering would break depending on grid rotation.
- Potentially fixed a client-side misprediction when unbuckling an entity from a north-facing chair.
:cl:
- fix: Borgs can stand up after falling again, and buckle layering should no longer break when the grid you are standing on is incorrectly oriented.

More Fixes

---

Resources/Prototypes/Catalog/Fills/Crates/fun.yml
Resources/Prototypes/Floof/Catalog/Cargo/cargo_fun.yml

Makes the upstream plushie and lizard plushie crates buyable by logistics/cargo. Attempted to balance cost around the fact that they don't contain all of the plushies like I believe the prizeballs do, and the prizeball crate is 5000. 
---
---
<p>
</p>
</details>
---
:cl:
- tweak: Logistics can now buy plushie crates

Make plushie crates buyable

---

Resources/Prototypes/Maps/Pools/default.yml

Adds submarine back to the default map pool as it has been patched and updated in #510.
Ironically, this map has survived being removed from rotation up until the moment the PR actually reworking it got merged.
:cl:
- fix: Submarine is back to the map pool.

Add submarine back into rotation

---

Resources/Prototypes/Entities/Objects/Specific/Service/vending_machine_restock.yml

Cherry-picks this PR: https://github.com/DeltaV-Station/Delta-v/pull/1768
Yes, I cherry-picked a PR for a single line of YAML. I'd do it again, too.
This does what it says on the tin, makes the CourierDrobe restockable using the generic clothing restock. 
---
---
<p>
I... I forgot to take a screenshot or video. It works, promise.
</p>
</details>
---
:cl:
- fix: CourierDrobes are now restockable with clothing restocks

Make CourierDrobes Restockable

---

Resources/Changelog/Floof.yml

Manually added a bunch of changelog entries from between January 26th and February 18th that were missing.
---
---
<p>
Nahhh, you know what changelogs look like.
</p>
</details>
---
:cl:
- fix: Added some missing changelog entries.

Restore Missing Changelog Entries

---

Resources/Locale/en-US/Floof/lathe/lathe-categories.ftl
Resources/Prototypes/DeltaV/Recipes/Lathes/clothing.yml
Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Resources/Prototypes/Floof/Recipes/Lathes/categories.yml
Resources/Prototypes/Floof/Recipes/Lathes/clothing.yml
Resources/Prototypes/Floof/Recipes/Lathes/sockoutfits.yml
Resources/Prototypes/Floof/Recipes/Lathes/uniformssocksect.yml
Resources/Prototypes/Nyanotrasen/Recipes/Lathes/clothing.yml
Resources/Prototypes/Recipes/Lathes/clothing.yml

Adds missing departmental thongs, thigh highs, and socks to uniform printer, adds clothing categories, and adds some other missing uniforms.
We have had problems with the lingerie items since their addition to the game. Adding them in any quantity to the departmental 'drobes causes restock cost balance issues, and many of them are _only_ available as starting loadout (a system which itself has significant issues). This pull request seeks to address these issues in a small way by making them accessible post round-start via the uniform printer.
There are a lot of items available in the uniform printer. Adding categories is proposed as a way to make it easier to use.
The atmospheric and roboticist uniform items were found to be missing from the list. Since these are equivalent to many other …

Uniform Printer Additions

---

Resources/Prototypes/Reagents/Consumable/Drink/drinks.yml
Resources/Prototypes/Reagents/Consumable/Drink/soda.yml

Ice is now a valid way to satiate thirst, but drinking a bucketful of ice is now a very bad idea.
From testing, a 30u glass is not enough to get an average human to frozen, but it will be more dangerous for smaller characters to drink large quantities. Nonetheless, it will never do more than 1 damage per 1u drank, so even the tiniest characters aren't going to die from drinking a glass.
By request, I also took a look at ice cream, but decided not to do what was requested and instead made both ice cream and cream satiate hunger. This is because fat (the primary component of both) is a known valid survival food. Cream breaks down into nutriment, and ice cream breaks down into nutriment and sugar. Both still satiate thirst.
---
:cl:
- tweak: Ice now satiates thirst, but also makes you cold. …

Ice Metabolizes to Water, Lowers Temperature, and Causes Damage Once Frozen

---

Content.Client/Chat/Managers/ChatManager.cs
Content.Client/UserInterface/Systems/Chat/ChatUIController.cs
Content.Client/UserInterface/Systems/Chat/Controls/ChannelFilterPopup.xaml.cs
Content.Client/UserInterface/Systems/Chat/Controls/ChannelSelectorPopup.cs
Content.Server/Chat/Commands/SubtleOOCCommand.cs
Content.Server/Chat/Systems/ChatSystem.cs
Content.Shared/Chat/ChatChannel.cs
Content.Shared/Chat/ChatSelectChannel.cs
Content.Shared/Chat/SharedChatSystem.cs
Resources/Locale/en-US/Floof/chat/ui/chat-box.ftl
Resources/Locale/en-US/chat/managers/chat-manager.ftl

This PR adds Sublte OOC made by april; requested by the floof team.
And while im at it; porting also filters for admins/players regarding suble.
Following PRs ported:
https://github.com/TheDenSS14/TheDen/pull/159 (Only Chat Changes)
https://github.com/TheDenSS14/TheDen/pull/163
---
:cl:
- add: Ported subtle OOC (Prefix: { )

Subtle OOC

---

Content.Server/Medical/Components/HealingComponent.cs
Content.Shared/Body/Part/BodyPartComponent.cs
Resources/Prototypes/Entities/Objects/Specific/Medical/healing.yml
Resources/Prototypes/Reagents/Consumable/Drink/alcohol.yml
Resources/Prototypes/Reagents/Consumable/Drink/drinks.yml
Resources/Prototypes/Reagents/medicine.yml

- Theobromine: increased the amount of THB added by drinks like coffee, tea, and their derivatives to 0.1 instead of 0.05, because otherwise drinking coffee and tea would never allow enough THB to accumulate in your body to deal damage (if you have an animal stomach that is). Some drinks already had this value set to 0.1 which allowed them to be poisonous to animals, as intended.
- Medical: EE has badly thrown medical balance off by introducing poorly thought out changes (namely, increasing the amount of healing topicals provide by a factor of 3 instead of nerfing space/fire damage that was the cause of that change). Those changes were introduced to floof in the commit b431d24f86f94433ea0c53982db83e40ef1d3f2c. Most of the changes there were reverted, except for the stack sizes of …

Medical Balance Tweaks and Fixes

---

Resources/Prototypes/DeltaV/Roles/Jobs/Justice/chief_justice.yml
Resources/Prototypes/Roles/Antags/nukeops.yml

Round 2153 was arguably a horrible round for both Security and Justice members involved. However, after some discussion with some fellow players and revelations, we found out that the whitelist system for Chief Justice is actually broken. Along with the CJ at the time not being whitelisted according to public sources within the Discord server.
This PR seeks to fix the aforementioned issue, which if not clear is as entails;
Currently at the moment you need 600 minutes and a "whitelist" to play as Chief Justice. However, due to an oversight in the YAML, this whitelist actually never existed.
For example, the `captain.yaml` utilizes the statement `whitelisted: true` to implement it. But for Chief Justice, this is instead utilizing the `!type;CharacterWhitelistRequirement` to attempt to …

Remove Deprecated JobPrototype Whitelist Requirements

---

Resources/Prototypes/Entities/Objects/Devices/pda.yml

Reparents senior PDAs and research assistant's PDAs to fix some issues like the missing glimmer monitor on research seniors and interns.
:cl:
- fix: Research seniors and interns should now have the glimmer monitor app installed on their PDAs by default.

Reparent some PDAs

---

Resources/Prototypes/CharacterItemGroups/Jobs/Command/captain.yml
Resources/Prototypes/CharacterItemGroups/Jobs/Command/commandUncategorized.yml
Resources/Prototypes/CharacterItemGroups/Jobs/Engineering/chiefEngineer.yml
Resources/Prototypes/CharacterItemGroups/Jobs/Medical/paramedic.yml
Resources/Prototypes/Floof/Loadouts/Jobs/Command/uncategorized.yml
Resources/Prototypes/Floof/Loadouts/Jobs/Engineering/chiefEngineer.yml
Resources/Prototypes/Floof/Loadouts/Jobs/Medical/paramedic.yml
Resources/Prototypes/Loadouts/Jobs/Command/captain.yml

Removed empty captain bags from captain loadouts. The filled captain bags are still there. Added filled paramedic bags. These are the bags that a player will spawn with without any loadouts, so loadout choices should at least have parity with that.
Added missing longcoat, turtleneck jumpsuit, and turtleneck jumpskirt to chief engineer's loadout.
Added administration HUD to command loadout. It's a point cheaper than the administration glasses because it lacks flash protection.
---
---
:cl:
- add: Filled paramedic bag loadouts
- add: Loadouts for chief engineer's longcoat, as well as turtleneck jumpsuit and jumpskirt
- add: Administration HUD command loadout
- remove: Removed unfilled captain bag loadouts. Filled captain bags remain.

Various Loadout Changes

---

Content.Server/Administration/Systems/AdminVerbSystem.Smites.cs
Content.Shared/Body/Systems/SharedBodySystem.Organs.cs

This cherry-pick from WizDen, number 29926 includes back end changes relating to organs and how they are handled.
This is necessary if we are to port stuff such as recent DeltaV merges that interact with organs in any manner. My PRs, #612 and #623 is reliant on these changes due to the usage of `GetBodyOrganEntityComps` and so on forth.
No change log is needed as this is purely a codebase change.
---

Cherry-Pick "Update Vomit Organ Smite to Not Use Component.owner (#29926)"

---

Content.Server/Paint/PaintSystem.cs
Content.Shared/Paint/PaintRemoverSystem.cs

Allows admins to use spray cans and soap on anything that can be/is painted that they can get verbs for. One less thing that they have to use VV for in a way that might break something.
---
:cl:
ADMIN:
- tweak: Admins can now adjust paint using spray cans/soap on any items as long as they can get verbs on them.

Admin Painting And Soaping

---

Resources/Prototypes/Entities/Objects/Weapons/Guns/Rifles/rifles.yml
Resources/Prototypes/Entities/Objects/Weapons/Guns/SMGs/smgs.yml

Added semi-automatic firemode to all rifles and SMGs, such as the AKMS, Lecter, and Drozd. This shouldn't affect balance at all, as single shots have always been achievable through lightly tapping the trigger (unless you're lagging a lot), and mostly improves *immersion*, *realism* and preventing the common occurrence of magdumping the cadet by accident.
(Help I am stuck in big font)
---
---
:cl: Nox38
- tweak: Added semi-auto firemode to all automatic weapons.

Select Fire Rifles

---

Content.Shared/Examine/ExamineSystemShared.cs

Ups the examine details visibility range from 3 to 16.
Would be nice if i knew how to make it not auto-close the window as well, but it's a step in the right direction.  
🆑 Fenny
- tweak: Examine range to 16 tiles so you no longer have to walk up to people and oogle them from point blank range to read about their heaving cleavage.

Examine Detail Range Increase

---

Resources/Prototypes/Floof/Traits/physical.yml
Resources/Prototypes/Roles/Antags/nukeops.yml
Resources/Prototypes/Roles/Antags/traitor.yml

Balance patch to prevent captain, security, and antags from being tiny.
Note that a full rework will be coming later to fix visual issues, make it harder to struggle out of inventories, and likely other tweaks based on feedback.
---
---
<p>
</p>
</details>
---
:cl:
- tweak: Captain, Security, and some antags can no longer be tiny

Tiny Trait Patch

---

Content.Shared/InteractionVerbs/SharedInteractionVerbsSystem.cs

Taken from here: https://github.com/Fansana/floof-frontier/pull/161
:cl:
- fix: Interaction verbs (looking, petting, etc) should no longer reveal the target's or user's identity.

Fix Interaction Verbs Revealing Identity

---

Resources/Prototypes/Catalog/VendingMachines/Inventories/chapel.yml
Resources/Prototypes/CharacterItemGroups/Jobs/Epistemics/chaplain.yml
Resources/Prototypes/Floof/Loadouts/Jobs/Epistemics/chaplain.yml

Added chaplain's stole and crucifix to chaplain loadout, added loadout groups to chaplain's lingerie and mantle, removed cost from chaplain's mantle, and replaced service headsets with epistemics headset in the chaplain's vendor.
The chaplain's mantle has no particular advantages over other free uniform outerwear, and has no reason to cost a point.
---
:cl:
- add: Added Chaplain's stole and crucifix to loadout.
- tweak: Removed cost from Chaplain's mantle loadout.

Add Missing Chaplain's Stole and Crucifix to Loadout
